version: "3.8"

services:
  memcached0:
    image: memcached
    ports:
      - "11210:11211"
    networks:
      - app-network

  hazelcast0:
    image: hazelcast/hazelcast
    ports:
      - "5700:5701"
    networks:
      - app-network

  redis0:
    image: redis
    command: redis-server --cluster-enabled yes --cluster-config-file /data/nodes.conf --appendonly no --port 6379
    ports:
      - "6379:6379"
      - "16379:16379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
