version: "3.8"

services:
  memcached0:
    image: memcached
    command: ["-m", "128m"]
    ports:
      - "11210:11211"
    networks:
      - app-network

  hazelcast0:
    image: hazelcast/hazelcast
    ports:
      - "5700:5701"
    networks:
      - app-network

  redis0:
    image: redis
    command: ["redis-server", "--appendonly", "yes", "--maxmemory", "8192"]
    ports:
      - "6370:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
