version: "3.8"

services:
  memcached0:
    image: memcached
    command: memcached -m 16384
    ports:
      - "11210:11211"
    networks:
      - app-network

  hazelcast0:
    image: hazelcast/hazelcast
    ports:
      - "5700:5701"
    networks:
      - app-network

  redis0:
    image: redis
    ports:
      - "6370:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
