version: "3.8"

services:
  memcached1:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network

  hazelcast1:
    image: hazelcast/hazelcast
    ports:
      - "5701:5701"
    networks:
      - app-network

  redis1:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
