version: "3.8"

services:
  memcached1:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network
  memcached2:
    image: memcached
    ports:
      - "11212:11211"
    networks:
      - app-network
  memcached3:
    image: memcached
    ports:
      - "11213:11211"
    networks:
      - app-network

  memcached4:
    image: memcached
    ports:
      - "11214:11211"
    networks:
      - app-network
  memcached5:
    image: memcached
    ports:
      - "11215:11211"
    networks:
      - app-network
  memcached6:
    image: memcached
    ports:
      - "11216:11211"
    networks:
      - app-network
  memcached7:
    image: memcached
    ports:
      - "11217:11211"
    networks:
      - app-network
  memcached8:
    image: memcached
    ports:
      - "11218:11211"
    networks:
      - app-network
  memcached9:
    image: memcached
    ports:
      - "11219:11211"
    networks:
      - app-network
  memcached10:
    image: memcached
    ports:
      - "11220:11211"
    networks:
      - app-network

  hazelcast1:
    image: hazelcast/hazelcast
    ports:
      - "5701:5701"
    networks:
      - app-network
  hazelcast2:
    image: hazelcast/hazelcast
    ports:
      - "5702:5701"
    networks:
      - app-network
  hazelcast3:
    image: hazelcast/hazelcast
    ports:
      - "5703:5701"
    networks:
      - app-network
  hazelcast4:
    image: hazelcast/hazelcast
    ports:
      - "5704:5701"
    networks:
      - app-network
  hazelcast5:
    image: hazelcast/hazelcast
    ports:
      - "5705:5701"
    networks:
      - app-network
  hazelcast6:
    image: hazelcast/hazelcast
    ports:
      - "5706:5701"
    networks:
      - app-network
  hazelcast7:
    image: hazelcast/hazelcast
    ports:
      - "5707:5701"
    networks:
      - app-network
  hazelcast8:
    image: hazelcast/hazelcast
    ports:
      - "5708:5701"
    networks:
      - app-network
  hazelcast9:
    image: hazelcast/hazelcast
    ports:
      - "5709:5701"
    networks:
      - app-network
  hazelcast10:
    image: hazelcast/hazelcast
    ports:
      - "5710:5701"
    networks:
      - app-network

  redis1:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  redis2:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - app-network
  redis3:
    image: redis
    ports:
      - "6381:6379"
    networks:
      - app-network
  redis4:
    image: redis
    ports:
      - "6382:6379"
    networks:
      - app-network
  redis5:
    image: redis
    ports:
      - "6383:6379"
    networks:
      - app-network
  redis6:
    image: redis
    ports:
      - "6384:6379"
    networks:
      - app-network
  redis7:
    image: redis
    ports:
      - "6385:6379"
    networks:
      - app-network
  redis8:
    image: redis
    ports:
      - "6386:6379"
    networks:
      - app-network
  redis9:
    image: redis
    ports:
      - "6387:6379"
    networks:
      - app-network
  redis10:
    image: redis
    ports:
      - "6388:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
