version: "3.8"

services:
  memcached0:
    image: memcached
    ports:
      - "11210:11211"
    networks:
      - app-network
  memcached1:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - app-network
  memcached2:
    image: memcached
    ports:
      - "11212:11211"
    networks:
      - app-network

  hazelcast0:
    image: hazelcast/hazelcast
    ports:
      - "5700:5701"
    networks:
      - app-network
  hazelcast1:
    image: hazelcast/hazelcast
    ports:
      - "5701:5701"
    networks:
      - app-network
  hazelcast2:
    image: hazelcast/hazelcast
    ports:
      - "5702:5701"
    networks:
      - app-network

  redis0:
    image: redis
    command: redis-server --appendonly yes --maxmemory 4096mb --maxmemory-policy allkeys-lru --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6370:6379"
    networks:
      - app-network
  redis1:
    image: redis
    command: redis-server --appendonly yes --maxmemory 4096mb --maxmemory-policy allkeys-lru --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6371:6379"
    networks:
      - app-network
  redis2:
    image: redis
    command: redis-server --appendonly yes --maxmemory 4096mb --maxmemory-policy allkeys-lru --cluster-enabled yes --cluster-config-file /data/nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6372:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
